language: node_js
node_js: stable
dist: trusty
sudo: required
addons:
  firefox: latest
  sauce_connect: true
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable
before_install:
- export TZ=America/Sao_Paulo
before_script:
- npm install -g bower web-component-tester
- bower install
script:
- xvfb-run wct --skip-plugin sauce
- if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then wct --skip-plugin local -s 'default';
  fi
env:
  global:
  - secure: YZ3RAwhAprs1BfhCwhi20DR1DXZmHYzqbRhtX7PC3OTyj6k9FnRaUVk5y7/z1Bri+CAoVgmyWMA7RbQAaPfccRQTM8p8g8eCv3W7Pqo36909VR/xnMIiuIdDj0FRFf1pT8sODNsDLx2LJXIaVpxYr3gPEXEDOugzBJz8duTOppsLn2fiMbADFWDxG7MyyFieRO6RSy/7ZuERAmTaBRgCBROnnP3mGmBRKvlBHtxqoII4pTeLppm81Pz5HAn4VRzTsZ69ykzgMkiIYPy6BOXM3o2cxbV8E3nqM7jFnILFBm+NBZl07z/UGcXcFTDFkjXJSvJqdJy8GoFmdUARhOBiygsfwF87yU5DCs1RYMw/1bKPkhJLgPtazkG5vdOyBX/1m1RzUo7WrcDrbcHHkdVFQNSefclhQAYzkIdX2WtLWeLFoRMszUIGKwjYz2bPLpl35KTZAro3WXtxEQAhZugRiTsdnnGJvMRLrWd5i9wYruXXUR+ZQ5Gf+Rv18ZfTSNEl/Pr4xWzvD04cBbm/NujDYKjscD2YhY8l8lYwnDc6gLastRRNI+XY8ZBKO+B78b1KpXBSmRa143LXq0ZOA1+mTa7VyY//8ZW/pRz42wZR+t8Za1t8vMLyRF84YRt7U9tOZ1xz9xf3Bx4ElkUJgfUqe3/DaC+SD5Bnv6H1IOnZ18w=
  - secure: kyQYb/w3HEdV4e5Xnl4/4Aqsxsz9jaz/2phl3BHkNsfYzCLgbsQ1WM9v/GmHJV3ZO7Lz2tkrliBfVVQK2oUfbyIxr59nPzLFrZa4Xo431SljdggW9t5ruBo8xAzi40A1ogAAMYUivd33JvzQdIYOgC44XC0+QV3jefMWDSbSnzn310sVDQAbZ55kcHREHx9x5I3Ofdh0Zy0MIXNfDFO2Zls/+vay7sDh5klrEM2EyGaUwRkEBjVXEoy3/S5BNVkFlWei4SehbSEIuXbvF7z+LbQm3iLPlFTdOHDuhguwetoJqJe6cTKE2kLkiVkPE8r2E6emr3FgF/wYM49GdiGYPKVxRMpVB3FjFI3qCq2+qkko93J+k5lJMiXxkh3rKH3xnmwjxbTy/axwZLwrsQXQZbKdjO0GFIEkmoYz2Z3/1X5V7sZ6SevRYLZWLUiVwr9ynqOXx3lyhKnGageoylH9qp94JC54PFLFEe1xyDrG6UBFIn+4F9LqEfZXwGUAwooy6Lt2s/+ns7rgbLvFqot66/XVY5yXfZhd9ODXaHgEmlGRDwEaNwwg3Kke4W7iWLok85C8msBfDO9ZIb2s4bN9qrUJCxU9tZY8eN+8gWuB4EmI4fXWuDVudEte9Qkma69TZ+VMiOeaIiYE/TdN8uLt9L4/bH6eYrq9MjGaTBxvitA=
